packaging_format = 2

id = "prestashop"
name = "Prestashop"
description.en = "Create a E-commerce Website"
description.fr = "Créer un site ecommerce"

version = "9.1.0~ynh1"

maintainers = []

[upstream]
license = "OSL-3.0"
website = "https://prestashop.com"
demo = "https://demo.prestashop.com/#/en/front"
userdoc = "https://doc.prestashop.com/display/PS17/Guide+de+l'utilisateur"
code = "https://github.com/PrestaShop/PrestaShop"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prestashop"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/Thatoo/prestashop_ynh/raw/refs/heads/v9-2/sources/prestashop_edition_basic_version_9.1.0-4.0.zip"
        sha256 = "7cb2f4a625c4e6ebc1a32799401529f4a14030e435a8e0ce58ad60c09f05b78b"
        in_subdir = false

        autoupdate.strategy = "latest_github_release"
        
    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.5-mbstring, php8.5-curl, php8.5-intl, php8.5-xmlrpc, php8.5-mysql, php8.5-gd, php8.5-xml, php8.5-cli, php8.5-zip"

    [resources.database]
    type = "mysql"
