packaging_format = 2

id = "prestashop"
name = "Prestashop"
description.en = "Create a E-commerce Website"
description.fr = "Créer un site ecommerce"

version = "8.1.2~ynh1"

maintainers = ["frju365"]

[upstream]
license = "OSL-3.0"
website = "https://prestashop.com"
demo = "https://demo.prestashop.com/#/en/front"
userdoc = "https://doc.prestashop.com/display/PS17/Guide+de+l'utilisateur"
code = "https://github.com/PrestaShop/PrestaShop"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prestashop"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrestaShop/PrestaShop/releases/download/8.1.2/prestashop_8.1.2.zip"
        sha256 = "e58faf24f543a179a7eb63f88665bb13c80a35615df7ae0267c7ad3de696e2c2"
        in_subdir = false
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.1-mbstring, php8.1-curl, php8.1-intl, php8.1-xmlrpc, php8.1-mysql, php8.1-gd, php8.1-xml, php8.1-cli, php8.1-zip"

    [resources.database]
    type = "mysql"
