packaging_format = 2

id = "prestashop"
name = "Prestashop"
description.en = "Create a E-commerce Website"
description.fr = "Créer un site ecommerce"

version = "8.0.4~ynh1"

maintainers = ["frju365"]

[upstream]
license = "OSL-3.0"
website = "https://prestashop.com"
demo = "https://demo.prestashop.com/#/en/front"
userdoc = "https://doc.prestashop.com/display/PS17/Guide+de+l'utilisateur"
code = "https://github.com/PrestaShop/PrestaShop"

[integration]
yunohost = ">= 11.1.21"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/prestashop"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/PrestaShop/PrestaShop/releases/download/8.0.4/prestashop_8.0.4.zip"
        sha256 = "a4603059d1b581d50a501eb70bd7a3557d13ea1edc43292ec96deae6b14b28f5"
        in_subdir = false
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server php8.2-mbstring php8.2-fpm php8.2-common php8.2-curl php8.2-intl php8.2-xmlrpc php8.2-mysql php8.2-gd php8.2-xml php8.2-cli php8.2-zip"

    [resources.database]
    type = "mysql"
