#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Updating database..."

ynh_mysql_db_shell $app <<< "UPDATE ${db_prefix}configuration SET value = '$domain' WHERE name = 'PS_SHOP_DOMAIN';"
ynh_mysql_db_shell $app <<< "UPDATE ${db_prefix}configuration SET value = '$domain' WHERE name = 'PS_SHOP_DOMAIN_SSL';"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
