#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Source app helpers
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)

#=================================================
# REMOVE THE SQL BDD
#=================================================

ynh_mysql_remove_db $db_name $db_name	# Suppression de la base de donnée et de l'utilisateur associé.

SECURE_REMOVE '/var/www/$app'	# Suppression du dossier de l'application

REMOVE_NGINX_CONF	# Suppression de la configuration nginx

REMOVE_FPM_CONF	# Suppression de la configuration du pool php-fpm

# Régénère la configuration de SSOwat
sudo yunohost app ssowatconf

echo -e "\e[0m"	# Restore normal color
