#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

ynh_app_setting_set_default --key=php_upload_max_filesize --value=1G
ynh_app_setting_set_default --key=php_memory_limit --value=512M
ynh_app_setting_set_default --key=php_max_execution_time --value=60

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="img override"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
# ynh_script_progression "Upgrading database..."

# pushd $install_dir
# 	php$php_version ./install/upgrade/upgrade.php
# popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
